# Site settings
title: Lucas Smith - Designer
email: lucas@volan.co
description: > # I am a Designer living in Alameda, CA and working for Earnest in San Francisco, CA.
baseurl: ""
url: "http://www.lucassmith.me"
# url: "http://localhost:4000"
twitter_username: volanStudio
github_username:  volanStudio

# Build settings
markdown: kramdown
permalink: /:categories/:title
exclude: ['s3_website.yml', 'README.md']
sass:
  style: :compressed
